0723_CRUD/learning_crud/learning_crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("post/", include("post.urls")),
]

0723_CRUD/learning_crud/post/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.main, name="main1"),
    path("post_list/", views.post_list, name="post_l"),
    path("post_list/<int:pk>/", views.post_detail, name="post_d"),
    path("post_create/", views.post_create, name="post_c"),
    # path("post_update/<int:pk>/", views.post_update, name="post_u"),
    # path("post_delete/<int:pk>/", views.post_delete, name="post_del"),
]

0723_CRUD/learning_crud/post/models.py
from django.db import models

# class PostList(models.Model):


class Post(models.Model):
    title = models.CharField(max_length=255, null=True)
    content = models.TextField(null=True)
    writer = models.CharField(max_length=255, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

0723_CRUD/learning_crud/post/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from . import models


def main(request):

    return render(request, "post/main.html")


def post_list(request):
    all_posts = models.Post.objects.all()
    ctx = {
        "posts": all_posts,
    }
    return render(request, "post/post_list.html", ctx)


def post_detail(request, pk):

    post1 = models.Post.objects.get(pk=pk)
    ctx = {
        "post": post1,
    }

    return render(request, "post/post_detail.html", ctx)


def post_create(request):
    if request.method == "POST":

        new_Post = models.Post.objects.create(
            title=request.POST.get("tit"),
            writer=request.POST.get("wri"),
            content=request.POST.get("con"),
        )
        new_pk = new_Post.pk
        return redirect(reverse("post:post_d", kwargs={"pk": new_pk}))

    else:

        return render(request, "post/post_create.html")

0723_CRUD/learning_crud/post/templates/post/main.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>안녕하세요</h1>
    <a href="{% url 'post:post_l'%}">게시판 이동</a>
  </body>
</html>

0723_CRUD/learning_crud/post/templates/post/post_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<form action="{% url 'post:post_c' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <h2>제목</h2><input type="text" name="tit">
    <h2>작성자</h2><input type="text" name="wri">
    <h2>내용:</h2><textarea type="text" name="con"></textarea>
    <button type="submit">작성</button>
</form>

    
</body>
</html>

0723_CRUD/learning_crud/post/templates/post/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ post.title }}</h1>
    <h2>{{ post.writer }}</h2>
    <h3>{{ post.updated_at}}</h3>
    <h4>{{ post.content }}</h4>
</body>
</html>

0723_CRUD/learning_crud/post/templates/post/post_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% for post in posts %}
        <div class="">
        <a href="{% url 'post:post_d' post.pk %}" class="">
            {{post.pk}}.{{post.title}}
        </a>
        </div>
    {% endfor %}
  </body>
</html>